version: '3'

networks:
    demo-network:
        #name: demo-network
        driver: bridge
        
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.5.0
        ports:
            - "2181:2181"
        environment: 
            ZOOKEEPER_CLIENT_PORT: 2181
        container_name: zookeeper
        volumes:
            - ./zookeeper/data:/var/lib/zookeeper/data
            - ./zookeeper/datalog:/var/lib/zookeeper/log
        networks: 
            - demo-network
    kafka:
        image: confluentinc/cp-kafka:5.5.0
        container_name: kafka
        depends_on: 
            - zookeeper
        ports:
            - "9092:9092"
        environment: 
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_ADVERTISED_HOST_NAME: kafka
        volumes:
            - ./kafka/data:/var/lib/kafka/data
        networks: 
            - demo-network
